name: flutter_native_pdf_viewer_example
description: Demonstrates how to use the flutter_native_pdf_viewer plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_pdf_viewer:
    path: ../

  path_provider: ^2.0.1

  http: ^0.13.0

  cupertino_icons: ^1.0.0

  file_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
