name: flutter_native_pdf_viewer_example
description: "Demonstrates how to use the flutter_native_pdf_viewer plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_native_pdf_viewer:
    path: ../
  http: ^1.2.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
