name: flutter_native_pdf_viewer
description: A lightweight PDF viewer for iOS and Android, using platform-native elements.
version: 2.0.0
author: 'cloudacy OG <office@cloudacy.com>'
homepage: 'https://cloudacy.com/'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_pdf_viewer
        pluginClass: FlutterNativePdfViewerPlugin
      ios:
        pluginClass: FlutterNativePdfViewerPlugin
