name: flutter_native_pdf_viewer
description: A lightweight PDF viewer for iOS and Android, using platform-native elements.
version: 4.0.0
homepage: 'https://cloudacy.com/'

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_pdf_viewer
        pluginClass: FlutterNativePdfViewerPlugin
      ios:
        pluginClass: FlutterNativePdfViewerPlugin
