name: flutter_native_pdf_viewer
description: A lightweight PDF viewer for iOS and Android, using platform-native elements.
version: 0.0.1
author: "cloudacy OG <office@cloudacy.com>"
homepage: "https://cloudacy.com/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_pdf_viewer
        pluginClass: FlutterNativePdfViewerPlugin
      ios:
        pluginClass: FlutterNativePdfViewerPlugin
